name: rlmol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.8
  - numpy=1.19.*
  - rdkit
  - pymatgen<=2021.2.13
  - pandas
  - tqdm
  - gym
  - psycopg2
  - sqlalchemy
  - pytest
  - pytest-cov
  - jupyterlab
  - seaborn
  - pyyaml
  - cclib
  - openbabel
  - pip
  - pip:
    - nfp
    - tensorflow
    - tensorflow-addons
    - "ray[rllib]"
