name: rlmol
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - rdkit
  - pymatgen
  - pandas
  - tqdm
  - gym
  - psycopg2
  - sqlalchemy
  - pytest
  - pytest-cov
  - jupyterlab
  - seaborn
  - pyyaml
  - pip
  - pip:
    - nfp
    - tensorflow
    - tensorflow-addons
