# coding: utf-8
# file generated by setuptools_scm
# don't change, don't track in version control
__version__ = version = '0.0.3.dev43+g2a8b133.d20220817'
__version_tuple__ = version_tuple = (0, 0, 3, 'dev43', 'g2a8b133.d20220817')
