from argparse import ArgumentParser

parser = ArgumentParser()
parser.add_argument("--min-atoms", default=4, type=int)
parser.add_argument("--max-atoms", default=12, type=int)
parser.add_argument("--max-num-bonds", default=20, type=int)
parser.add_argument("--max-num-actions", default=64, type=int)
parser.add_argument("--sa-score-threshold", default=4.0, type=float)
parser.add_argument("--stop-timesteps", default=int(1e6), type=int)
parser.add_argument("--stop-iters", default=1e3, type=int)
parser.add_argument("--stop-reward", default=1.0, type=float)
parser.add_argument("--run", default="PPO", type=str)
parser.add_argument("--num-gpus", default=0, type=int)
parser.add_argument("--num-cpus", default=8, type=int)
parser.add_argument("--num-samples", default=1, type=int)
parser.add_argument("--log-level", default="WARN", type=str)
parser.add_argument("--local-dir", default="../log", type=str)
parser.add_argument("--redis-password", default=None, type=str)
parser.add_argument("--node-ip-address", default="127.0.0.1", type=str)
